### ISSUE TITLE
Open and closing parentheses

### ISSUE THREAD

**Issue by corelon** [madmalik/mononoki#12] opened 2016-03-15 14:38 UTC
I noticed that the opening and closing parentheses "(" and ")" are not aligned. Is that by design or a bug?

**Comment by jdw1996** [comment] 2016-03-15 21:06
I don't know if it helps in figuring out why this is, but when I make the font size bigger (eg. 16 point), they are aligned.

**Comment by madmalik** [comment] 2016-03-16 18:10
This may be some kind of hinting glitch. Font rendering is dark magic...

What system do you use? Maybe i can recreate it

**Comment by jdw1996** [comment] 2016-03-16 20:46
I'm using Ubuntu 14.04 LTS and it happens in every program I've tried it in (Emacs, Vim, GNOME Terminal, Geany, LibreOffice Writer, Firefox) for most font sizes under 16 (in particular, 12, 13, and 15).

One thing I think is worth noting is that, in most cases, the right parenthesis is slightly lower than the left one, but in some very small sizes, it is the other way around. That would make me think it isn't an issue with the font itself.

**Comment by corelon** [comment] 2016-03-17 00:37
In my case it is Windows 7, with at least Sublime Text that I have tried.

**Comment by tante** [comment] 2016-05-19 09:22
Same on a Windows10 Box here.

**Comment by jjuel** [comment] 2016-05-19 16:00
Windows 7 in Visual Studio 11pt and they do not align.

**Comment by facundomedica** [comment] 2016-05-19 17:59
I'm having the same issue on Windows 10 in Visual Studio (running on VMWare Fusion) at 12. At 8 they look fine, but maybe because of the screen resolution(?) At 16 is not looking good.
Quite weird, because it looks fine in Atom on OS X.
![screen shot 2016-05-19 at 2 55 35 pm](https://cloud.githubusercontent.com/assets/14063057/15403968/cadca05e-1dd1-11e6-9ee0-5687c84955a1.png)

**Comment by madmalik** [comment] 2016-05-19 19:05
That is very... strange. I'll think i have to set up a bunch of operating systems in virtual box and test it there. 

I'm pretty sure it's a hinting issue. After dealing with various font rasterizers, i'll never complain about browser incompatibilities again. :P


So, i don't know what the problem is, but i'm pretty sure i'll will be able to solve this in the next days.

**Comment by seanlaguna** [comment] 2016-07-10 00:23
Any update on this? Biggest sticking point from switching from monoOne to this.

**Comment by corelon** [comment] 2016-10-31 12:16
Hi again,

Any update on the issue? Has it been resolved?

Many thanks

**Comment by fitojb** [comment] 2017-01-30 10:35
You might want to run [ttfautohint](https://www.freetype.org/ttfautohint) on the fonts to remove or lessen some of these glitches.

**Comment by sergeevabc** [comment] 2018-03-21 10:08
Err… @madmalik, where are you?

**Comment by manuel-uberti** [comment] 2019-01-10 08:58
Sorry to chime in just to ask for updates, but: are there any?

**Comment by samjross** [comment] 2019-05-17 08:32
Windows 10 / Webstorm, having this issue. This font is GORGEOUS but this one reason stops me from using it. Literally the best font I've ever seen apart from this.

**Comment by madmalik** [comment] 2022-09-05 21:45
tracking this in issue #79 now, and it might possibly be fixed in the upcoming release

**Closed by madmalik** 2022-09-05 21:45 UTC
