### ISSUE TITLE
Diaeresis not visible.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [madmalik/mononoki#52] opened 2017-01-31 03:14 UTC
Diaeresis not visible on **Ä** and **Ö** when font size is less than 10 and `"no_antialias"` in Sublime Text won't solve the problem, also **Å** looks like **Ă**. 
![screenshot](https://cloud.githubusercontent.com/assets/11806048/22451016/e4c9c584-e7a5-11e6-8ec9-97545b434461.png)

**Comment by felis-blue** [comment] 2023-01-12 10:37
We tested this with the current version of the font  in Sublime on Mac, Windows and Linux and can't reproduce the issue, the diaeresis and ring diacritic look ok (the example is font size 8):
<img width="363" alt="screenshot of ÄÖÜÅ" src="https://user-images.githubusercontent.com/51200413/212041722-4784c9ac-c8d5-4a25-b083-63f8a43f2551.png">

Closing this issue as resolved, if you're still getting this rendering problem with the current version of mononoki, please let us know here, including the following details: Which operating system is affected? Which software is affected, does it only happen in Sublime or are other programs affected as well? And which version of the font are you using, TTF or OTF? Thank you!

**Closed by felis-blue** 2023-01-12 10:37 UTC
Labels: issue:rendering
