### ISSUE TITLE
Equal '=' character is shown as hyphen '-' inside double quote string. In Intellij IDE, windows os.

### ISSUE THREAD

**Issue by kauser-cse-buet** [madmalik/mononoki#43] opened 2016-06-06 09:50 UTC
While editing in intellij ide I found a strange problem. Inside double quote string while I type equal sign "=" it shows as "-". e.g.

val abc = "result -" //It should show as "result =".

![mononoki-intellij-equal](https://cloud.githubusercontent.com/assets/2320050/15818274/53fd0a9c-2bfe-11e6-9425-8ab124c09c66.PNG)

**Comment by sliceofcode** [comment] 2016-06-07 06:00
Looks like a duplicate of #38.

**Comment by madmalik** [comment] 2016-06-09 11:38
like ssliceofcode said, it's a duplicate. I'm still trying to figure out what is happening

**Closed by madmalik** 2016-06-09 11:38 UTC
