### ISSUE TITLE
Uncentered and half-height characters in terminals

### ISSUE THREAD

**Issue by Silejonu** [madmalik/mononoki#95] opened 2022-10-19 18:59 UTC
In version 1.4, characters are reduced in height and uncentered in terminal windows. This behaviour was not present in 1.3 and downwards.

I tested (and successfully reproduced) this issue in GNOME Terminal and GNOME Console, on Arch Linux and Fedora 36. Both the .ttf and .otf files are affected.

All the other applications I tested (gedit, Text Editor, LibreOffice Writer) seem unaffected.

mononoki 1.3 behaviour:
![Screenshot from 2022-10-19 20-47-37](https://user-images.githubusercontent.com/48565914/196780073-404e7ddf-00c2-4bc0-a1d9-3c465c664510.png)

mononoki 1.4 behaviour:
![Screenshot from 2022-10-19 20-39-29](https://user-images.githubusercontent.com/48565914/196780111-b083535c-630c-4fd3-8313-bd24bf12bec6.png)

**Comment by madmalik** [comment] 2022-10-19 19:02
Thanks for creating the issue. Is this happening for the otf version or the ttf version?

**Comment by Silejonu** [comment] 2022-10-19 19:04
> Thanks for creating the issue. Is this happening for the otf version or the ttf version?

I realised I forgot the mention it immediately after submitting the issue and edited it, but you're too quick. ^^

It happens with both the otf and ttf versions.

**Comment by datMaffin** [comment] 2022-10-29 20:28
Hmm. I did not yet try to reproduce this, or try to dig deeper into this issue, but just comparing the metrics, there seems to be a small change:
*1.4 .ttf is on the left, the 1.3 ttf is on the right*
![image](https://user-images.githubusercontent.com/29998721/198850454-ce0efb2e-919c-4da1-8d55-b3979aaf1e76.png)
The "Really use Typo metrics" checkbox seems to now be enabled.

FontForge describes the "Really use Typo metrics" field as:
![image](https://user-images.githubusercontent.com/29998721/198850581-543dfecb-123a-4e09-8c35-dabedd9d2f96.png)

The `HHead Line Gap` is also different, but according to FontForge, this is only used on a mac.
However, I think that the old value of 0 makes more sense, because the "ascent" and "decent" is already the *big* value of 900 and 250; adding even more spacing via the line gap seems redundant. 
But I do not know how it renders on macOS, so maybe its fine.

Definitely looks weird...
It feels, though, as if the "Typo Ascent", "Typo Descent" and "Typo Line Gap" are used. But it is weird that Gnome Terminal would include the "Typo Line Gap" to size its cursor.

**Comment by madmalik** [comment] 2022-10-31 12:12
> Hmm. I did not yet try to reproduce this, or try to dig deeper into this issue, but just comparing the metrics, there seems to be a small change: _1.4 .ttf is on the left, the 1.3 ttf is on the right_ ![image](https://user-images.githubusercontent.com/29998721/198850454-ce0efb2e-919c-4da1-8d55-b3979aaf1e76.png) The "Really use Typo metrics" checkbox seems to now be enabled.

I updated glyphs from version 2 to version 3, maybe that changed some defaults. I'm gonna dig into this

**Comment by datMaffin** [comment] 2022-11-04 21:26
I gave the current mononoki ttf a try in GNOME Terminal 3.28.2 (Ubuntu 18.04), and I was not able to reproduce it:
![image](https://user-images.githubusercontent.com/29998721/200077312-b89edd50-c86d-4fc4-8060-a2a107dae9b7.png)

**Comment by Silejonu** [comment] 2022-11-05 11:16
I just tested on Ubuntu 22.04, and I have the same issue.

**Comment by madmalik** [comment] 2022-11-07 11:11
I could reproduce the issue under Linux Mint in gnome terminal myself. I've installed FontForge and changed the "really use typo metrics" and it doesn't make a difference.

I'm gonna play around with the configuration and try if a can find out whats causing it

**Comment by madmalik** [comment] 2022-11-19 16:56
I found the relevant settings in glyphs. It ended up being both settings, that needed to be changed for it to be displayed properly: The "Really use typo metric" checkbox and the "HHead Line Gap" setting. Please nobody ask me why, it's black magic to me 😬 but should be fixed now! Thank you @datMaffin for nudging me in the right direction!

**Closed by madmalik** 2022-11-19 16:56 UTC
Labels: issue:rendering
