### ISSUE TITLE
"(" and ")" should be mirrored

### ISSUE THREAD

**Issue by ghost** [madmalik/mononoki#79] opened 2021-03-17 12:36 UTC
It looks off and quite distracting.
![image](https://user-images.githubusercontent.com/78950913/111467895-42d92980-8725-11eb-860c-26dafd7cdc2e.png)
![image](https://user-images.githubusercontent.com/78950913/111467946-53899f80-8725-11eb-970f-f2357ee6c9d8.png)

**Comment by ad1tyawagh** [comment] 2021-03-17 21:57
I second this. Please fix the misalignment.

**Comment by Lisoph** [comment] 2021-04-21 12:52
Personally I kinda like this, it adds some character, but looks like it's a bug. Other brackets don't have this.

I've also noticed that the higher the font size, the smaller the visual error (VSCode, Windows), but maybe that's just me.

| 14px | 24px | 34px |
|:----:|:----:|:----:|
| ![image](https://user-images.githubusercontent.com/3426722/115555389-baafec00-a2af-11eb-96f3-3d01a80d7027.png) | ![image](https://user-images.githubusercontent.com/3426722/115555858-488bd700-a2b0-11eb-9838-e6b4692f2167.png) | ![image](https://user-images.githubusercontent.com/3426722/115555951-648f7880-a2b0-11eb-8bb8-ec1ce09ef40c.png) |

**Comment by datMaffin** [comment] 2021-07-04 18:35
Following, is a guess I have about the parenthesis issue:

The source, using cubic bezier, of the parenthesis glyphs is perfectly symmetrical for `(` and `)`. The exported ttf (and woff) use quadratic bezier curves, which somehow results in asymmetry between `(` and `)` that might play into the result.

Source (cubic bezier):
![image](https://user-images.githubusercontent.com/29998721/124395627-68566700-dd05-11eb-977c-845c6fa9cc92.png)

Exported ttf (quadratic bezier):
![image](https://user-images.githubusercontent.com/29998721/124395730-f3cff800-dd05-11eb-978b-7393aac1a15c.png)



The top of the left parenthesis is pretty much identical to the bottom of the right parenthesis (and vice-versa):
(VsCode on windows)
![image](https://user-images.githubusercontent.com/29998721/124395492-b323af00-dd04-11eb-8834-b235ec53e404.png)
This corresponds to the way how the exported curve, using quadratic bezier, looks like.


FontForges conversion is in the aspect of symmetry better (though, pretty horrible in a different way xD):
![image](https://user-images.githubusercontent.com/29998721/124395863-da7b7b80-dd06-11eb-8f60-04caaed3a71c.png)

Resulting in VsCode rendering of:
![image](https://user-images.githubusercontent.com/29998721/124395918-1f9fad80-dd07-11eb-8647-9643df98e0a8.png)


---

Hinting might also be involved.

**Comment by madmalik** [comment] 2021-08-15 09:30
I'm currently trying to figure out how to persuade the export to not do that stuff. Meh, this sucks. Maybe i have to repaint the parens completely to get around it

**Comment by cata0309** [comment] 2021-11-27 19:49
I support this idea! Having this
![image](https://user-images.githubusercontent.com/35623921/143720311-35987d94-79c7-40e8-a425-b2fff44d4c18.png)
makes me feel uncomfortable.
@madmalik sorry for the ping, did you managed to look into the issue in much depth?

**Comment by madmalik** [comment] 2022-09-11 16:31
I have investigated this issue to the best of my ability, but was unable to pinpoint the reason for this rendering issue. Unfortunately I also was unable to reproduce it in my own environment (MacOS), making further investigation difficult. I have therefore decided to redraw the parens characters for version 1.4, in hopes that the slightly changed shape will lead to more consistent rendering across all font sizes and rendering engines. I would very much appreciate any feedback on how the new parens are behaving in [version 1.4](https://github.com/madmalik/mononoki/releases/download/1.4/mononoki.zip)!

Useful information to include in your feedback: 

* The OS and program you're using
* The effected font size(s)
* If you're using the ttf or the otf version
* If possible, a screenshot

Thanks everyone for your patience and cooperation as I'm figuring this out!

**Comment by Lisoph** [comment] 2022-09-12 08:19
> I would very much appreciate any feedback on how the new parens are behaving in [version 1.4](https://github.com/madmalik/mononoki/releases/download/1.4/mononoki.zip)!

Looks good now! Tested under Windows 10 (21H2); 8pt, 9pt, 11pt, 13pt, 20pt; otf; VSCode and Notepad.

**Comment by madmalik** [comment] 2022-09-12 08:38
> Looks good now! Tested under Windows 10 (21H2); 8pt, 9pt, 11pt, 13pt, 20pt; otf; VSCode and Notepad.

thats great to hear! Did you test the otf or the ttf files?

**Comment by Lisoph** [comment] 2022-09-12 11:52
> > Looks good now! Tested under Windows 10 (21H2); 8pt, 9pt, 11pt, 13pt, 20pt; otf; VSCode and Notepad.
> 
> thats great to hear! Did you test the otf or the ttf files?

OTF, but hang on, something's wrong. Now a lot of characters look *really* incosistent, especially `u` and `e`.

VSCode (13px):

![image](https://user-images.githubusercontent.com/3426722/189645898-071289e4-a2a1-48a9-ba0d-dac04741e012.png)

Notepad (11pt):

![image](https://user-images.githubusercontent.com/3426722/189645992-eedba075-8b05-4248-bcb6-e5d861f3bf54.png)

on Windows 10 (21H2). I'm going to test the TTF version in a second.

**Comment by madmalik** [comment] 2022-09-12 15:12
Since the redraw seems to have fixed the parens rendering issue, I'm closing this issue. If someone is still encountering this on version 1.4, please reopen!

I've opened a new issue (#94) for the faulty otf rendering.

**Closed by madmalik** 2022-09-12 15:12 UTC
Labels: issue:rendering
