### ISSUE TITLE
The bold italic version of mononoki font is detected as a separate font

### ISSUE THREAD

**Issue by Case3y** [madmalik/mononoki#109] opened 2023-05-06 05:44 UTC
When I use windows terminal, I found that the blod italic version of mononoki font is detected as a separate font. I can choose mononoki BoldItalic. And there was no blod italic version when I choose mononoki font in Git Bash.

I intall the ttf font on my Windows system.
<img width="806" alt="屏幕截图 2023-05-06 133639" src="https://user-images.githubusercontent.com/71315026/236602738-fda2fc33-358b-4b63-8f2f-0affba6bf95f.png">
<img width="451" alt="屏幕截图 2023-05-06 133618" src="https://user-images.githubusercontent.com/71315026/236602750-60f13070-69fe-4b07-ae53-c13e85deba47.png">

**Comment by datMaffin** [comment] 2023-05-11 18:34
Sounds like a duplicate of the resolved #49. Are you sure you are using a recent version of mononoki? I believe if you search for fonts in the windows settings you can see the version number of the installed font.

**Comment by Case3y** [comment] 2023-05-12 07:42
> Sounds like a duplicate of the resolved #49. Are you sure you are using a recent version of mononoki? I believe if you search for fonts in the windows settings you can see the version number of the installed font.

Thanks for your replay. The version of mononoki is 1.0006. My system language is Simplified Chinese. It also have same problem when I use another version (1.0004)

**Comment by madmalik** [comment] 2023-05-13 09:35
I'm gonna try to reproduce the issue. Is this Windows 10 or 11?

**Comment by madmalik** [comment] 2023-05-13 10:05
I've tested it on Windows and it is correctly recognized as a single font family.
![image](https://github.com/madmalik/mononoki/assets/1328396/0bd2f6ce-c5f3-453c-b191-6186be622e35)

I suspect that this is an issue with the windows installation. I am gonna close the issue for now - if someone knows steps to reproduce it please write a comment here and I will reopen it.

**Closed as completed by madmalik** 2023-05-13 10:05 UTC

**Comment by datMaffin** [comment] 2023-05-13 17:38
I checked it now also on windows (reinstalled the most recent mononoki release), and in the settings it seems to be correctly grouped. However, the Windows terminal really is still listing them separately:

![image](https://github.com/madmalik/mononoki/assets/29998721/b3593f49-f8b4-4262-a259-569dff194827)

**Comment by Case3y** [comment] 2023-07-10 04:12
I solved the problem using this method proposed in #49， I delete the "Preferred Name" and "Preferred Styles"

![屏幕截图 2023-07-10 121133](https://github.com/madmalik/mononoki/assets/71315026/40f220ef-e1ea-4871-a310-3f7b462459db)


What worked for me on Windows 7 SP1 is:

* Open `mononoki-BoldItalic.ttf` with FontForge.

* Choose "Element" menu -> "Font Info".

* Choose "TTF Names" tab in the appeared "Font Information" window, and remove the "Preferred Styles" entry with its right-click menu.

* Re-export the TTF via "File" menu -> "Generate Fonts".

It seems Windows is extraordinarily picky on many font properties.

_Originally posted by @richardgv in https://github.com/madmalik/mononoki/issues/49#issuecomment-447848343_
